TESTS = sanity_tacc sanity_work mumpsi64 hdf5_tacc hdf5_work
TEST = mumpsi64
include ../Make.common

.PHONY: work tacc
work :
	echo "ERROR rule unimplemented"

clean ::
	@rm -f sanity mumpsi64 hdf5 fortran
