#!/bin/bash
## NOTE THIS FILE IS AUTOGENERATED BY ../submit_test.sh
#SBATCH -J petsc_tacc_test
#SBATCH -o petsc_tacc_test.o%j
#SBATCH -e petsc_tacc_test.e%j
#SBATCH -p skx
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:00:00        # Run time (hh:mm:ss)
#SBATCH -A A-ccsc       # Allocation name (req'd if you have more than 1)

# we're not sure from where this package is invoked
if [ -d petsc ] ; then
   cd petsc
elif [ -d ../petsc ] ; then
   cd ../petsc
fi

eval ./tacc_tests.sh -v 3.21
