#!/bin/bash

function usage () {
    echo "Usage: $0 [ -l ] [ -v nn.nn ] package"
    echo "    -l : local mode; otherwise tacc mode"
}
    
if [ $# -eq 0 -o "$1" = "-h" ] ; then
    usage && exit 0
fi

mode=tacc
version=
while [ $# -gt 1 ] ; do
    if [ $1 = "-h" ] ; then
	usage && exit 0
    elif [ $1 = "-l" ] ; then
	mode=local && shift
    elif [ $1 = "-v" ] ; then
	shift && version=$1 && shift
    else
	echo "Unrecognized option: <<$1>>"
	usage && exit 1
    fi
done

package=$1
host=$( hostname | cut -d '.' -f 2 )
export queue
case $host in
    ( "frontera" ) queue=small ;;
    ( "stampede3" ) queue=skx ;;
    ( * ) queue=normal ;;
esac
echo && echo "On host ${host} using queue=${queue}"

batchfile=sbatch_${package}_${host}.sh
cat >${batchfile} <<EOF
#!/bin/bash
## NOTE THIS FILE IS AUTOGENERATED BY $0
#SBATCH -J ${package}_${mode}_test
#SBATCH -o ${package}_${mode}_test.o%j
#SBATCH -e ${package}_${mode}_test.e%j
#SBATCH -p ${queue}
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:00:00        # Run time (hh:mm:ss)
#SBATCH -A A-ccsc       # Allocation name (req'd if you have more than 1)

# we're not sure from where this package is invoked
if [ -d ${package} ] ; then
   cd ${package}
elif [ -d ../${package} ] ; then
   cd ../${package}
fi

eval ./${mode}_tests.sh $( if [ ! -z "${version}" ] ; then echo "-v ${version}" ; fi )
EOF

echo && echo "Submitting $(pwd)/${batchfile}"
sbatch ${batchfile}

echo
