-include ../../../petscdir.mk

EXAMPLESMATLAB   = ex5m.m ex29view.m
CLEANFILES       = ex5f90t

include ${PETSC_DIR}/lib/petsc/conf/petscvariables
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

ex55: ex55.o ex55k.o

