#!/bin/bash

####
#### Do not look at this file:
#### it is converted to an actual job script
#### through the makefile.
####

#SBATCH   -p QUEUE
#SBATCH   -J pylNAME
#SBATCH   -o pylaunchertestNAME.o%j
#SBATCH   -e pylaunchertestNAME.o%j
#SBATCH   --ntasks-per-node 1
#SBATCH   -N NODES
#SBATCH   -t 0:40:00
#SBATCH -A A-ccsc                  # replace by your own project

if [ -z "$TACC_PYTHON_DIR}" ] ; then 
    echo "Please load python module outside job script"
    exit 1
fi

## for local testing:
#export PYTHONPATH=..:${PYTHONPATH}
export NGPUS=NGPUS
echo "PYTHONPATH: ${PYTHONPATH}"
echo "Running EXECUTABLE on queue=QUEUE"

SSH RUN EXECUTABLE.py
